services:
  app:
    build: .
    container_name: product-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=product_db
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - product-network

  webserver:
    image: nginx:alpine
    container_name: product-api-webserver
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - product-network

  db:
    image: mysql:8.0
    container_name: product-api-db
    environment:
      MYSQL_DATABASE: product_db
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - product-network

volumes:
  dbdata:

networks:
  product-network: